version: "3"

services:

  node:    
    image: node 
    container_name: mjv-project
    build: ./ 
    # Mesmo que `docker run -t`
    tty: true
    # Mesmo que `docker run -i`
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório atual, com todos os dados do projeto, 
      # dentro do diretório /app
      - ./:/app
    depends_on:  
      - mongodb
    # na notação porta_de_fora:porta_de_dentro
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017/mjv-project
  
  mongodb:
    image: mongo
    container_name: mjv-project-db
    volumes:
      - ./:/app
    restart: always
    ports:

      - 27017:27017

networks:

  default:
    name: mjv-project-net


